import numpy as np

array = np.array(list(range(1,10)))
print("===============================================")
print(array.shape)
print("===============================================")
array_mod = array.reshape(3,3)
print(array_mod)
print("===============================================")
array_mod2 = array.reshape(-1, 3)
print(array_mod2)
print("===============================================")
array_volteado = array_mod2.transpose()
print(array_volteado)
print("===============================================")
array_chato = array_mod.flatten()
print(array_chato)
print("===============================================")
array_ravel = array_mod.ravel()
print(array_ravel)